### ISSUE TITLE
velocity-animate is not installed with Ember CLI 2.3.0-beta.2

### ISSUE THREAD

**Issue by zoltan-nz** [taras/ember-cli-velocity#11]
I just created a new app with Ember CLI 2.3.0-beta.2.

```
$ ember new test-app
```

Installed ember-cli-velocity

```
$ ember install ember-cli-velocity
```

Try to launch the server

```
$ ember s
```

Get this error message:

```
➜  test-app git:(master) ✗ ember s
version: 2.3.0-beta.2
Cannot find module 'velocity-animate'
Error: Cannot find module 'velocity-animate'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.require.resolve (internal/module.js:23:19)
    at Class.treeForVendor (/Users/szines/projects/temp/test-app/node_modules/ember-cli-velocity/index.js:14:60)
    at Class._treeFor (/Users/szines/projects/temp/test-app/node_modules/ember-cli/lib/models/addon.js:322:31)
    at Class.treeFor (/Users/szines/projects/temp/test-app/node_modules/ember-cli/lib/models/addon.js:292:19)
    at /Users/szines/projects/temp/test-app/node_modules/ember-cli/lib/broccoli/ember-app.js:439:20
    at Array.map (native)
    at EmberApp.addonTreesFor (/Users/szines/projects/temp/test-app/node_modules/ember-cli/lib/broccoli/ember-app.js:437:30)
    at EmberApp._processedVendorTree (/Users/szines/projects/temp/test-app/node_modules/ember-cli/lib/broccoli/ember-app.js:858:29)
    at EmberApp._processedExternalTree (/Users/szines/projects/temp/test-app/node_modules/ember-cli/lib/broccoli/ember-app.js:888:21)
```

Solution: manually add `velocity-animate` package to `package.json`, but I guess it could be automatically added. Maybe something changed in the CLI api recently?

**Comment by taras** [comment]
What version of npm are you using?

**Comment by runspired** [comment]
This is a confirmed bug I haven't had time to fix.  I believe we just need to `return` the result here.

https://github.com/EmberSherpa/ember-cli-velocity/blob/master/blueprints/ember-cli-velocity/index.js#L8

**Comment by zoltan-nz** [comment]
Latest npm, 3.7.1, node is v5.5.0

**Comment by Keeo** [comment]
+1

**Comment by cemarte** [comment]
Hey @runspired, I'm using ember-cli 2.3.0, tried your solution here and it seems to fix the problem. It is also causing a bug in [ember-velocity-mixin](https://github.com/EmberSherpa/ember-velocity-mixin) addon when installing though **ember install ember-velocity-mixin**.
